spring:
  profiles:
    active: local
  jpa:
    show-sql: true
spring.batch.job.name: ${job.name:NONE}
logging:
  level:
    org.springframework.batch: DEBUG
---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
---
spring.config.activate.on-profile: mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver