spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security_oauth2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

oauth2:
  kakao:
    client-id: f07f3819a47565895db9f6baf4cb18da
    client-secret: 9M3ObmBLIppP7JX8okbDhxtRrCtadzB3
    redirect-uri: http://localhost:8080/oauth2/callback/KAKAO
    scope:
      - "profile_nickname"
  google:
    client-id: 1064904822166-rhivkmljvsip9vc3p5b2nknv4uebnrjs.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/oauth2/callback/GOOGLE
    scope:
      - "email"
      - "profile"
app:
  client-base-url: http://localhost:3000