spring:
  config:
    import:
      - classpath:application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security_oauth2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
app:
  client-base-url: http://localhost:3000